[IV-23-23] Objetivo 4
shvtwp/cuidarDependencia pull request #22
Opened 2023-12-13 19:09 UTC by shvtwp

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [x] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

Ahora mismo solo está implementada la lógica de negocio del primer milestone

2023-12-14 08:30 UTC, manuelvico0102 requested changes
Buenas, voy a ser tu revisor para este objetivo. También te recomiendo que deberías crear más issues para ir indicando lo que vas haciendo y cuando hagas un commit hacer referencia a ese issue en vez de a la historia de usuario directamente.

2023-12-14 08:30 UTC, manuelvico0102 commented on docs/herramientas_tests.md
> +
Hay algunos criterios que mencionas, pero luego en las diferentes opciones a elegir no las mencionas.
Además, es recomendable usar [Snyk Advisor](https://snyk.io/advisor/) para comparar.

2023-12-14 08:30 UTC, manuelvico0102 commented on docs/herramientas_tests.md
> +
Creo que sería conveniente que comentases más opciones de librerías de aserciones, como algunas relacionadas con tu lenguaje seleccionado.

2023-12-14 08:30 UTC, manuelvico0102 commented on test/horario_test.ts
> +    function todasLasHorasAsignadas(horario: Horario): boolean {
Las funciones que has declarado en el test pienso que es parte de tu lógica de negocio, entonces no creo que sea muy buena práctica declararlas en el archivo para el test

2023-12-14 10:09 UTC, shvtwp commented on test/horario_test.ts
> +    function todasLasHorasAsignadas(horario: Horario): boolean {
Hola! Es que son funciones que no necesito para la lógica de negocio como tal, pero sí para testearla, entonces no me queda muy claro por qué colocarlas en, por ejemplo, horario.ts

2023-12-14 11:04 UTC, shvtwp commented on docs/herramientas_tests.md
> +
Solucionado en 27f436a

2023-12-14 11:05 UTC, shvtwp commented on docs/herramientas_tests.md
> +
Solucionado en 27f436a

2023-12-14 12:11 UTC, PabloBarTo commented on test/horario_test.ts
> +    function todasLasHorasAsignadas(horario: Horario): boolean {
Buenas! Sinceramente yo creo que están bien esas funciones ahí, ya que si solo se usan para probar que funcionan los test se podría implementar donde están implementados. Sin embargo dejaría que el profesor le echara un vistazo por si el considera que no deberían de estar ahí y tienen que estar en otro lado.
No resuelvas esta conversación para que luego el profesor pueda revisarlo y cuando soluciones todo lo que te ha comentado @manuelvico0102, que creo que solo queda arreglar lo de los issues, mencionamos al profesor.

2023-12-14 17:30 UTC, manuelvico0102 approved these changes

2023-12-14 18:46 UTC, shvtwp commented
@JJ listo para revisión.

2023-12-14 18:47 UTC, JJ commented on test/horario_test.ts
> +    function todasLasHorasAsignadas(horario: Horario): boolean {
Yo creo que la cuestión no es si deben estar en la lógica de negocio o en el test, sino si deben estar en este fichero o en otro fichero; más adelante decidir dónde exactamente debe estar ese fichero. En todo caso si se ha planteado la necesidad de escribir esas funciones, habrá tenido que ser como solución a un problema. Si el problema está relacionado directamente con la HU, es lógicamente parte de la lógica de negocio; si sólo son funciones auxiliares para los tests, y por tanto sólo indirectamente relacionados con la lógica de negocio , lo lógico es que estén en el directorio de test; pero en cualquiera de los casos parece más conveniente, por modularización, que estén aparte.

2023-12-14 19:06 UTC, JJ requested changes
Gracias a @manuelvico0102 y @PabloBarTo por la retroalimentación y gracias a @shvtwp por actuar tan rápidamente; pero me temo que en este caso es necesario dar un paso atrás y seguir las buenas prácticas: sólo se desarrolla código para resolver problemas que estén bien expresados en issues, porque es la única forma de garantizar que se cubren las necesidades del usuario. Por favor, hazlo así.

2023-12-14 19:06 UTC, JJ commented on docs/herramientas_tests.md
> +Usaré la opción ofrecida por la librería estándar de Deno para no tener
REalmente no hay tanta diferencia en Deno entre unas y otras; deno no lo incluye en su distribución por defecto y tienen que bajarse igualmente y cachearse. Puede ofrecerte una pequeña ventaja de mantenimiento, pero otras opciones si están bien actualizadas pueden ser también muy interesantes.

2023-12-14 19:06 UTC, JJ commented on drakefile.ts
> +    sh("deno test test/horario_test.ts");
¿Has probado a no poner explícitamente el nombre del test? Más adelante tendrás que hacer más, posiblemente.

2023-12-14 19:06 UTC, JJ commented on lib/cuidador.ts
> +   public getNombre(): string {
Ya en el [objetivo 2 se señaló que se usaran sólo los getters y setters que fueran necesarios](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido). Además, TS/JS tienen una forma específica para definir getters, si fuera necesario hacerlo.

2023-12-14 19:06 UTC, JJ commented on lib/cuidador.ts
> +   public setHorasOcupadas(hora: number, duracion: number){
Los setters son aún más discutibles que los getters. Por varias razones
1. La clase se llama "cuidador" y le estás encargando que incluya en su estado las horas en las que está ocupado/a. Las clases deben tener un solo cometido, y pro el nombre parece que se trata de los datos generales del cuidador.
2. Por otro lado, también estás haciendo un diseño en el que conviertes cuidador en entidad, al ser mutable; en vez de gestionar la entidad las horas ocupadas, es la entidad la que tiene que llamar al cuidador para establecer las horas ocupadas. Esto puede causar problemas por la indirección, pero también por el control del estado.

2023-12-14 19:06 UTC, JJ commented on lib/cuidador.ts
> +      public horasOcupadas: Array<boolean> = new Array(168).fill(false),
El problema con esta línea modificada en fe94d2c es que estás modificando directamente el código apuntando a la historia de usuario #3. En general, hay que seguir el mismo procedimiento que en el objetivo 2: crear issues que representen una serie de problemas, y a partir de ahí desarrollar el código. La HU normalmente expresa el problema desde el punto de vista del cliente, y es imposible deducir directamente del mismo la lógica de negocio: hay que seguir un procedimiento, una vez más *domain driven design*, describiendo los diferentes problemas y creando las estructuras de datos y funcionalidad necesaria.

2023-12-14 19:06 UTC, JJ commented on lib/cuidador.ts
> +      if (hora + duracion > 168){
Es una buena práctica usar siempre constantes con nombre, en vez de literales. Adicionalmente, esta línea la has modificado en el mismo ticket indicado arriba, y sólo apunta a la historia de usuario, con lo que es complicado o imposible, para quien vea el código, entender si es correcto o no.

2023-12-14 22:44 UTC, shvtwp commented on lib/cuidador.ts
> +   public setHorasOcupadas(hora: number, duracion: number){
No estoy segura de haberlo entendido bien, lo he modificado pero me gustaría aclararlo en clase

2023-12-14 22:44 UTC, shvtwp commented
@JJ Listo para revisión

2023-12-15 07:45 UTC, JJ reviewed
Queda un comentario por resolver; le doy un vistazo sobre la marcha cuando lo hagas.

2023-12-15 07:45 UTC, JJ commented on drakefile.ts
> +    sh("deno test test/horario_test.ts");
Por favor, resuelve todos los comentarios con cambios en la línea o en otras líneas indicando el commit en el que se ha resuelto.

2023-12-15 11:35 UTC, shvtwp commented on test/horario_test.ts
> +    function todasLasHorasAsignadas(horario: Horario): boolean {
Solucionado en a0cecb3

2023-12-15 11:36 UTC, shvtwp commented on docs/herramientas_tests.md
> +Usaré la opción ofrecida por la librería estándar de Deno para no tener
Solucionado en 1d98d5d

2023-12-15 11:37 UTC, shvtwp commented on drakefile.ts
> +    sh("deno test test/horario_test.ts");
Solucionado en 60813f1

2023-12-15 11:37 UTC, shvtwp commented on lib/cuidador.ts
> +   public getNombre(): string {
Solucionado en fd73353

2023-12-15 11:37 UTC, shvtwp commented on lib/cuidador.ts
> +   public setHorasOcupadas(hora: number, duracion: number){
Solucionado en c269cbd

2023-12-15 11:38 UTC, shvtwp commented on lib/cuidador.ts
> +      if (hora + duracion > 168){
Solucionado en 87a69c3

2023-12-15 11:42 UTC, shvtwp commented on lib/cuidador.ts
> +      public horasOcupadas: Array<boolean> = new Array(168).fill(false),
Solucionado en fd73353

2023-12-15 12:24 UTC, JJ approved these changes
👍

2023-12-15 12:43 UTC, merged