[IV-23-24] Objetivo 1
shvtwp/cuidarDependencia pull request #5
Opened 2023-10-02 13:47 UTC by shvtwp

**Sobre los milestones**

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?

* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?

* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?

* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?

* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?

* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un concepto vago, una funcionalidad o una tarea?

* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?

* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?

* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?

* [x] ¿El milestone 0 es mínimo *y* viable?

* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?

* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

**Sobre las historias de usuario**

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?

* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?

* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?

* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-10-02 16:31 UTC, carlosservi commented
Hola me ha tocado revisar tu proyecto. Voy a mirar que cosas creo que puedes mejorar.

2023-10-02 16:55 UTC, puchy22 requested changes
Hola buenas me ha tocado revistarte el proyecto, aquí te dejo algunos cambios que me parecen importantes para avanzar al suguiente objetico. Un saludo y suerte :dizzy:

2023-10-02 16:55 UTC, puchy22 commented on docs/HUs.md
> +Me llamo Pablo y tengo 24 años. Desde hace unos años mi abuela tiene Alzheimer, por lo que no podemos dejarla sola. A mi familia y a mí nos gustaría contar con un horario que se ajuste a la disponibi
Creo que a la historia le falta más contexto para que se entienda del todo bien. No queda del todo claro cuáles son las necesidades del usuario. Por ejemplo, cuando se refiere a sobrecargar a alguien, ¿quiere decir que tome más turnos a lo largo de un período de tiempo o que los turnos sean demasiado seguidos? Creo que sería conveniente ser un poco más específico con las necesidades del usuario, ya que en el próximo objetivo será otro compañero quien trabaje con estas historias y tiene que saber exactamente cuál es el problema.

2023-10-02 16:55 UTC, puchy22 commented on docs/HUs.md
> +Mi nombre es María y tengo 46 años. Hace tiempo que a mi padre le diagnosticaron ELA y necesita estar acompañado en todo momento. Mis dos hermanos y yo trabajamos a veces a la misma hora, por lo que
Creo que no se refleja del todo bien el problema en esta historia de usuario. ¿El problema es que no se encuentra una trabajadora que cuide del padre o el hecho de coordinar los horarios con esa nueva trabajadora? En caso de que sea lo segundo, creo que no queda del todo claro que este sea el problema, además que la lógica de negocio sería la misma que en la primera historia de usuario, por lo que se podría comprimir en una sola.

2023-10-02 16:55 UTC, puchy22 commented on docs/milestones.md
> +## [M1] Implementación de un horario cubierto
No usaría la palabra "Implementación". Los milestones deben ser productos finales, no tareas a hacer. En los títulos de estos, basta con dejar claro cual es la lógica necesaria para una Historia de Usuario determinada funcione.

2023-10-02 17:35 UTC, shvtwp commented
@puchy22 Hola, he hecho algunos cambios en las cosas que me has indicado, ¿podrías volver a revisarlo y decirme?

2023-10-03 09:55 UTC, PabloBarTo commented
Hola, a mi también me ha tocado ser tu revisor.

2023-10-03 10:36 UTC, puchy22 commented
@shvtwp Yo ya lo veo bien, lo único que hay una falta de ortografía en la HU, "que esa situación se dé". Por lo demás por mí está todo correcto. A ver si algún otro revisor tiene algo más que añadir :+1: .

2023-10-04 14:02 UTC, shvtwp commented
@PabloBarTo @carlosservi Hola, ¿tenéis algún consejo sobre algo que pudiese mejorar? ¡Gracias!

2023-10-04 15:41 UTC, carlosservi commented
Hola @shvtwp , se me ocurre que podrías hacer otra historia de usuario para la cuidadora, la cuál necesita saber con antelación los horarios de trabajo, por ejemplo. Espero te sirva de ayuda.

2023-10-04 16:44 UTC, PabloBarTo approved these changes
Teniendo en cuenta los cambios que has realizado tras las indicaciones de @puchy22 yo creo que ya queda claro las necesidades del usuario, así que creo que ya podría estar listo para revisión.

2023-10-04 16:44 UTC, PabloBarTo commented on docs/HUs.md
> +Me llamo Pablo y tengo 24 años. Desde hace unos años mi abuela tiene Alzheimer, por lo que no podemos dejarla sola. A mi familia y a mí nos gustaría contar con un horario que se ajuste a la disponibi
Teniendo en cuenta los cambios que has realizado tras las indicaciones de @puchy22 yo creo que ya queda claro las necesidades del usuario, así que creo que ya podría estar listo para revisión.

2023-10-04 16:46 UTC, shvtwp commented
@JJ

2023-10-04 17:00 UTC, JJ requested changes
Gracias a @carlosservi @puchy22 y @PabloBarTo por el trabajo realizado. Creo que te has acercado bastante, pero aparte de lo comentado, quizás podrías añadir alguna historia de usuario por una persona que tenga circunstancias especiales (como que sólo admita ocuparse si no hay nadie disponible), quizás asignar prioridades a unos frente a otros, o finalmente otra HU que tenga en cuenta una serie de circunstancias para aconsejar (o no) un ingreso en un centro de día o permanente (que, desgraciadamente, suele ser el final en este tipo de casos)
Quizás haya algún manual del SAS para atención a dependientes de este estilo y las reglas que se deben seguir, si lo hay aportarlo al user journey también ayudará a poder modelizar más correctamente el problema.

2023-10-04 17:00 UTC, JJ commented on docs/HUs.md
> +Me llamo Pablo y tengo 24 años. Desde hace unos años mi abuela tiene Alzheimer, por lo que no podemos dejarla sola. A mi familia y a mí nos gustaría contar con un horario que se ajuste a la disponibi
Me da la impresión de que le falta un poco de detalle. No sé, por ejemplo, cuanta antelación hace falta para contratar a una persona profesional, ni qué tipo de restricciones laborales tienen. Tampoco cuantas horas seguidas puede estar una persona, ni con cuanta frecuencia se generan estos turnos.
Quizás sería conveniente que hicieras un *user journey*, como comentamos en el guión. No siempre es necesario, pero cuando hay detalles que no se pueden poner en la HU porque la cargaría mucho es mejor hacer ese tipo de documento.

2023-10-04 19:39 UTC, shvtwp commented
@JJ Listo para revisión

2023-10-05 05:11 UTC, JJ approved these changes
👍 Por favor, resuelve los comentarios como se indica antes de fusionar (y en lo sucesivo)

2023-10-05 05:11 UTC, JJ commented on docs/HUs.md
> +Me llamo Pablo y tengo 24 años. Desde hace unos años mi abuela tiene Alzheimer, por lo que no podemos dejarla sola. A mi familia y a mí nos gustaría contar con un horario que se ajuste a la disponibi
Si no resuelves el comentario es muy difícil saber qué se ha hecho, en general. Puedes resolverlo desde el menú, añadiendo un comentario en el que digas en qué commit se ha resuelto; eso en el caso de que no modifiques directamente la línea en la que se ha hecho el comentario.

2023-10-05 06:37 UTC, shvtwp commented on docs/HUs.md
> +Me llamo Pablo y tengo 24 años. Desde hace unos años mi abuela tiene Alzheimer, por lo que no podemos dejarla sola. A mi familia y a mí nos gustaría contar con un horario que se ajuste a la disponibi
He añadido las historias de usuario y los milestones 2 y 3, además del user journey.

2023-10-05 06:39 UTC, merged